name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" > deploy_key && chmod 600 deploy_key
          ssh -o StrictHostKeyChecking=no -i deploy_key $SSH_USER@$SSH_HOST << 'EOF'
            cd /home/ubuntu/hng12/book-api/app/
            git pull origin main
            docker-compose down
            docker-compose up --build -d
          EOF